#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "____  ___________    ___________________");  
$L "\   \/  /\_____  \  /   _____/\______   \ "); 
$L " \     /  /   |   \ \_____  \  |     ___/"); 
$L " /     \ /    |    \/        \ |    |   ");  
$L "/___/\  \\_______  /_______  / |____|   "); 
$L "      \_/        \/        \/           ");
$L "Welcome to Android `getprop ro.build.version.release` / XOSP-`getprop ro.xosp.release`-`getprop ro.xosp.revision`";
