# Copy S+ Reborn Extras

WALLPAPERS_VENDOR_PATH := vendor/reborn/prebuilt/common/etc/customization/content/com/sonyericsson/wallpaperpicker/wallpapers
WALLPAPERS_SYSTEM_PATH := system/etc/customization/content/com/sonyericsson/wallpaperpicker/wallpapers

PRODUCT_COPY_FILES += \
    $(WALLPAPERS_VENDOR_PATH)/A1.png:$(WALLPAPERS_SYSTEM_PATH)/A1.png \
		$(WALLPAPERS_VENDOR_PATH)/A3.png:$(WALLPAPERS_SYSTEM_PATH)/A3.png \
		$(WALLPAPERS_VENDOR_PATH)/A4.png:$(WALLPAPERS_SYSTEM_PATH)/A4.png \
		$(WALLPAPERS_VENDOR_PATH)/A5.png:$(WALLPAPERS_SYSTEM_PATH)/A5.png \
		$(WALLPAPERS_VENDOR_PATH)/A6.png:$(WALLPAPERS_SYSTEM_PATH)/A6.png \
		$(WALLPAPERS_VENDOR_PATH)/B1.png:$(WALLPAPERS_SYSTEM_PATH)/B1.png \
		$(WALLPAPERS_VENDOR_PATH)/B2.png:$(WALLPAPERS_SYSTEM_PATH)/B2.png \
		$(WALLPAPERS_VENDOR_PATH)/B3.png:$(WALLPAPERS_SYSTEM_PATH)/B3.png \
		$(WALLPAPERS_VENDOR_PATH)/B4.png:$(WALLPAPERS_SYSTEM_PATH)/B4.png \
		$(WALLPAPERS_VENDOR_PATH)/B5.png:$(WALLPAPERS_SYSTEM_PATH)/B5.png \
		$(WALLPAPERS_VENDOR_PATH)/C1.png:$(WALLPAPERS_SYSTEM_PATH)/C1.png \
		$(WALLPAPERS_VENDOR_PATH)/C2.png:$(WALLPAPERS_SYSTEM_PATH)/C2.png \
		$(WALLPAPERS_VENDOR_PATH)/C3.png:$(WALLPAPERS_SYSTEM_PATH)/C3.png \
		$(WALLPAPERS_VENDOR_PATH)/C4.png:$(WALLPAPERS_SYSTEM_PATH)/C4.png \
		$(WALLPAPERS_VENDOR_PATH)/C6.png:$(WALLPAPERS_SYSTEM_PATH)/C6.png \
		$(WALLPAPERS_VENDOR_PATH)/C7.png:$(WALLPAPERS_SYSTEM_PATH)/C7.png \
		$(WALLPAPERS_VENDOR_PATH)/C8.png:$(WALLPAPERS_SYSTEM_PATH)/C8.png \
		$(WALLPAPERS_VENDOR_PATH)/C9.png:$(WALLPAPERS_SYSTEM_PATH)/C9.png \
		$(WALLPAPERS_VENDOR_PATH)/C10.png:$(WALLPAPERS_SYSTEM_PATH)/C10.png \
		$(WALLPAPERS_VENDOR_PATH)/C11.png:$(WALLPAPERS_SYSTEM_PATH)/C11.png \
		$(WALLPAPERS_VENDOR_PATH)/C12.png:$(WALLPAPERS_SYSTEM_PATH)/C12.png \
		$(WALLPAPERS_VENDOR_PATH)/C13.png:$(WALLPAPERS_SYSTEM_PATH)/C13.png \
		$(WALLPAPERS_VENDOR_PATH)/C14.png:$(WALLPAPERS_SYSTEM_PATH)/C14.png \
		$(WALLPAPERS_VENDOR_PATH)/C15.png:$(WALLPAPERS_SYSTEM_PATH)/C15.png \
		$(WALLPAPERS_VENDOR_PATH)/Dark.png:$(WALLPAPERS_SYSTEM_PATH)/Dark.png \
		$(WALLPAPERS_VENDOR_PATH)/Light.png:$(WALLPAPERS_SYSTEM_PATH)/Light.png

