# Copy XOSP Extras

WALLPAPERS_VENDOR_PATH := vendor/xosp/prebuilt/common/etc/customization/content/com/sonyericsson/wallpaperpicker/wallpapers
WALLPAPERS_SYSTEM_PATH := system/etc/customization/content/com/sonyericsson/wallpaperpicker/wallpapers

PRODUCT_COPY_FILES += \
		$(WALLPAPERS_VENDOR_PATH)/A1.png:$(WALLPAPERS_SYSTEM_PATH)/A1.png \
		$(WALLPAPERS_VENDOR_PATH)/A1_small.png:$(WALLPAPERS_SYSTEM_PATH)/A1_small.png \
		$(WALLPAPERS_VENDOR_PATH)/B1.png:$(WALLPAPERS_SYSTEM_PATH)/B1.png \
		$(WALLPAPERS_VENDOR_PATH)/B1_small.png:$(WALLPAPERS_SYSTEM_PATH)/B1_small.png \
		$(WALLPAPERS_VENDOR_PATH)/C1.png:$(WALLPAPERS_SYSTEM_PATH)/C1.png \
		$(WALLPAPERS_VENDOR_PATH)/C1_small.png:$(WALLPAPERS_SYSTEM_PATH)/C1_small.png \
		$(WALLPAPERS_VENDOR_PATH)/D1.png:$(WALLPAPERS_SYSTEM_PATH)/D1.png \
		$(WALLPAPERS_VENDOR_PATH)/D1_small.png:$(WALLPAPERS_SYSTEM_PATH)/D1_small.png \
		$(WALLPAPERS_VENDOR_PATH)/E1.png:$(WALLPAPERS_SYSTEM_PATH)/E1.png \
		$(WALLPAPERS_VENDOR_PATH)/E1_small.png:$(WALLPAPERS_SYSTEM_PATH)/E1_small.png \
		$(WALLPAPERS_VENDOR_PATH)/F1.png:$(WALLPAPERS_SYSTEM_PATH)/F1.png \
		$(WALLPAPERS_VENDOR_PATH)/F1_small.png:$(WALLPAPERS_SYSTEM_PATH)/F1_small.png \
		$(WALLPAPERS_VENDOR_PATH)/G1.png:$(WALLPAPERS_SYSTEM_PATH)/G1.png \
		$(WALLPAPERS_VENDOR_PATH)/G1_small.png:$(WALLPAPERS_SYSTEM_PATH)/G1_small.png \
		$(WALLPAPERS_VENDOR_PATH)/H1.png:$(WALLPAPERS_SYSTEM_PATH)/H1.png \
		$(WALLPAPERS_VENDOR_PATH)/H1_small.png:$(WALLPAPERS_SYSTEM_PATH)/H1_small.png
